version: '2'
services:
    adoptme-app:
        image: adoptme
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://adoptme-mysql:3306/adoptme?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    adoptme-mysql:
        extends:
            file: mysql.yml
            service: adoptme-mysql
